server:
  port: 9090
  servlet:
    session:
      #配置session的有效时间为30天
      timeout: 2592000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-security?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    hikari:
      username: root
      password: yibo
      # mysql 6.x以上 com.mysql.cj.jdbc.Driver
      # mysql 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: auth-server
  redis:
    database: 1
    host: 127.0.0.1
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password:
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode:
      #添加后，redis中的key为spring:session:myproject
      #namespace: myproject
mybatis:
  type-aliases-package: com.yibo.server.domain.entity
  mapper-locations: classpath:mapper/*.xml
mapper:
  identity: MYSQL
  not-empty: false